#pragma once

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <GLM/glm.hpp>
#include <GLM/ext.hpp>
#include "RenderEngine.h"
#include "Command/RegisterShaderDefaults.h"
#include "Command/RegisterTextureDefaults.h"
#include "Command/SetActiveScene.h"
#include "Command/LoadTexture.h"
#include "Model/Model.h"
#include "Model/Mesh.h"
#include "Model/ModelLoader.h"
#include "Material/Material.h"
#include "Material/PBRMaterial.h"
#include "Shaders/Shader.h"
#include "Camera/Camera.h"
#include "Scene.h"
#include "../Util/skybox_util.h"
#include "../Util/shape_util.h"
#include "Light/PointLight.h"